# Generated by Django 4.2.1 on 2023-06-17 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_delete_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
