# Generated by Django 4.2.1 on 2023-06-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='shared_with',
        ),
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
        migrations.AddField(
            model_name='note',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='note',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
    ]
