# Generated by Django 4.2.1 on 2023-06-21 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0006_note_shared_with_note_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='user',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='note',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='note',
            name='video_file',
        ),
        migrations.AddField(
            model_name='note',
            name='notes_type',
            field=models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('video', 'Video')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
