# Generated by Django 4.2.1 on 2023-06-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_rename_user_note_owner_remove_note_audio_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='notes_type',
        ),
        migrations.AddField(
            model_name='note',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='note',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
    ]
